import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const WAD_PATH = resolve(process.cwd(), 'doom1.wad')
const OUT_PATH = resolve(process.cwd(), 'src/e1m1-data.ts')

interface Lump {
  offset: number
  size: number
  name: string
}

function readLumpName(buf: Buffer, offset: number): string {
  let name = ''
  for (let i = 0; i < 8; i++) {
    const c = buf[offset + i]
    if (c === 0) break
    name += String.fromCharCode(c)
  }
  return name
}

function parseDirectory(buf: Buffer): Lump[] {
  const numLumps = buf.readInt32LE(4)
  const dirOffset = buf.readInt32LE(8)
  const lumps: Lump[] = []
  for (let i = 0; i < numLumps; i++) {
    const base = dirOffset + i * 16
    lumps.push({
      offset: buf.readInt32LE(base),
      size: buf.readInt32LE(base + 4),
      name: readLumpName(buf, base + 8),
    })
  }
  return lumps
}

function findMapLumps(lumps: Lump[], mapName: string): Record<string, Lump> {
  const start = lumps.findIndex(l => l.name === mapName)
  if (start < 0) throw new Error(`Map ${mapName} not found`)
  const wanted = new Set(['THINGS', 'LINEDEFS', 'SIDEDEFS', 'VERTEXES', 'SEGS', 'SSECTORS', 'NODES', 'SECTORS', 'REJECT', 'BLOCKMAP'])
  const out: Record<string, Lump> = {}
  for (let i = start + 1; i < lumps.length; i++) {
    if (!wanted.has(lumps[i].name)) break
    out[lumps[i].name] = lumps[i]
  }
  return out
}

const wad = readFileSync(WAD_PATH)
const lumps = parseDirectory(wad)
const map = findMapLumps(lumps, 'E1M1')

const vertsLump = map['VERTEXES']
const numVerts = vertsLump.size / 4
const verts: number[] = []
for (let i = 0; i < numVerts; i++) {
  const o = vertsLump.offset + i * 4
  verts.push(wad.readInt16LE(o), wad.readInt16LE(o + 2))
}

const linedefsLump = map['LINEDEFS']
const numLinedefs = linedefsLump.size / 14
const linedefs: number[] = []
for (let i = 0; i < numLinedefs; i++) {
  const o = linedefsLump.offset + i * 14
  const v1 = wad.readUInt16LE(o)
  const v2 = wad.readUInt16LE(o + 2)
  const rightSide = wad.readUInt16LE(o + 10)
  const leftSide = wad.readUInt16LE(o + 12)
  linedefs.push(v1, v2, rightSide, leftSide)
}

const sidedefsLump = map['SIDEDEFS']
const numSidedefs = sidedefsLump.size / 30
const sidedefSectors: number[] = []
for (let i = 0; i < numSidedefs; i++) {
  const o = sidedefsLump.offset + i * 30
  sidedefSectors.push(wad.readUInt16LE(o + 28))
}

const sectorsLump = map['SECTORS']
const numSectors = sectorsLump.size / 26
const sectorLight: number[] = []
for (let i = 0; i < numSectors; i++) {
  const o = sectorsLump.offset + i * 26
  const light = wad.readUInt16LE(o + 20)
  sectorLight.push(Math.max(0, Math.min(255, light)))
}

const thingsLump = map['THINGS']
const numThings = thingsLump.size / 10
let playerX = 0
let playerY = 0
let playerAngleDeg = 0
for (let i = 0; i < numThings; i++) {
  const o = thingsLump.offset + i * 10
  const type = wad.readUInt16LE(o + 6)
  if (type === 1) {
    playerX = wad.readInt16LE(o)
    playerY = wad.readInt16LE(o + 2)
    playerAngleDeg = wad.readInt16LE(o + 4)
    break
  }
}

// Convert Doom angle (0=east, 90=north in Doom map space where +Y is north)
// to our internal radians where ray dy = -sin(angle) accounts for the flip.
const playerAngleRad = (playerAngleDeg * Math.PI) / 180

const out = `// Auto-generated by scripts/process-wad.ts — do not edit
export const VERTS: Int16Array = new Int16Array([${verts.join(',')}])
export const LINEDEFS: Uint16Array = new Uint16Array([${linedefs.join(',')}])
export const SIDEDEF_SECTORS: Uint16Array = new Uint16Array([${sidedefSectors.join(',')}])
export const SECTOR_LIGHT: Uint8Array = new Uint8Array([${sectorLight.join(',')}])
export const PLAYER_X: number = ${playerX}
export const PLAYER_Y: number = ${playerY}
export const PLAYER_ANGLE: number = ${playerAngleRad}
`

writeFileSync(OUT_PATH, out)
console.log(`Wrote ${OUT_PATH}: ${numVerts} verts, ${numLinedefs} linedefs, ${numSidedefs} sidedefs, ${numSectors} sectors, player at (${playerX}, ${playerY}) angle ${playerAngleDeg}deg`)
